version: '2'
services:
  web:
    build: .
    command: ./start
    cap_add:
      - SYS_PTRACE
    volumes:
      - .:/notifications-api
    volumes_from:
      - ruby-bundle
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      notification_net:
        ipv4_address: 192.168.255.11
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=12345
      - DB_NAME=notifications
      - DB_HOST=db
      - REDIS_SERVER=redis://redis:6379
  
  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf  # Montar el archivo de configuración
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]  # Usar el archivo de configuración
    networks:
      notification_net:
        ipv4_address: 192.168.255.12

  ruby-bundle:
    image: busybox
    volumes:
      - /ruby-bundle
    networks:
      notification_net:
        ipv4_address: 192.168.255.13

networks:
  notification_net:
      driver: bridge
      driver_opts:
        com.docker.network.driver.mtu: 1400
      ipam:
        driver: default
        config:
          - subnet: 192.168.255.8/29
            gateway: 192.168.255.9
