development:
  adapter: redis
  url: <%= ENV['REDIS_SERVER'] %>
  channel_prefix: your_app_development

production:
  adapter: redis
  url: <%= ENV['REDIS_SERVER'] %>
  channel_prefix: your_app_production
